export const APPLICATION_CREATE_REQUEST = 'APPLICATION_CREATE_REQUEST';
export const APPLICATION_CREATE_SUCCESS = 'APPLICATION_CREATE_SUCCESS';
export const APPLICATION_CREATE_FAIL = 'APPLICATION_CREATE_FAIL';
export const APPLICATION_CREATE_RESET = 'APPLICATION_CREATE_RESET';

export const APPLICATION_PAY_REQUEST = 'APPLICATION_PAY_REQUEST';
export const APPLICATION_PAY_SUCCESS = 'APPLICATION_PAY_SUCCESS';
export const APPLICATION_PAY_FAIL = 'APPLICATION_PAY_FAIL';
export const APPLICATION_PAY_RESET = 'APPLICATION_PAY_RESET';

export const APPLICATION_APPROVE_REQUEST = 'APPLICATION_APPROVE_REQUEST';
export const APPLICATION_APPROVE_SUCCESS = 'APPLICATION_APPROVE_SUCCESS';
export const APPLICATION_APPROVE_FAIL = 'APPLICATION_APPROVE_FAIL';
export const APPLICATION_APPROVE_RESET = 'APPLICATION_APPROVE_RESET';

export const APPLICATION_DETAILS_REQUEST = 'APPLICATION_DETAILS_REQUEST';
export const APPLICATION_DETAILS_SUCCESS = 'APPLICATION_DETAILS_SUCCESS';
export const APPLICATION_DETAILS_FAIL = 'APPLICATION_DETAILS_FAIL';

export const APPLICATION_MINE_LIST_REQUEST = 'APPLICATION_MINE_LIST_REQUEST';
export const APPLICATION_MINE_LIST_SUCCESS = 'APPLICATION_MINE_LIST_SUCCESS';
export const APPLICATION_MINE_LIST_FAIL = 'APPLICATION_MINE_LIST_FAIL';

export const APPLICATION_LIST_REQUEST = 'APPLICATION_LIST_REQUEST';
export const APPLICATION_LIST_SUCCESS = 'APPLICATION_LIST_SUCCESS';
export const APPLICATION_LIST_FAIL = 'APPLICATION_LIST_FAIL';

export const APPLICATION_DELETE_REQUEST = 'APPLICATION_DELETE_REQUEST';
export const APPLICATION_DELETE_SUCCESS = 'APPLICATION_DELETE_SUCCESS';
export const APPLICATION_DELETE_FAIL = 'APPLICATION_DELETE_FAIL';
export const APPLICATION_DELETE_RESET = 'APPLICATION_DELETE_RESET';

export const APPLICATION_SUMMARY_REQUEST = 'APPLICATION_SUMMARY_REQUEST';
export const APPLICATION_SUMMARY_SUCCESS = 'APPLICATION_SUMMARY_SUCCESS';
export const APPLICATION_SUMMARY_FAIL = 'APPLICATION_SUMMARY_FAIL';
